workspace:
  base: /go
  path: src/github.com/kgantsov/todogo

pipeline:
  # tests:
  #   image: golang:latest
  #   commands:
  #     - go get -u github.com/golang/dep/cmd/dep
  #     - dep ensure --vendor-only
  #     - go test ./... -race
  #   when:
  #     event: [ push ]

  build:
    image: plugins/docker
    secrets: [ docker_username, docker_password ]
    repo: kgantsov/todogo_api
    tag: latest
    file: Dockerfile
    when:
      event: [ push, tag ]

  ssh:
    image: appleboy/drone-ssh
    host: 51.15.86.4
    username: root
    port: 22
    secrets: [ ssh_key ]
    script:
      - echo hello
      - echo world
      - cd /apps/todogo/
      - docker-compose pull
      - docker-compose stop api
      - docker-compose up -d api
    when:
      event: [ tag ]

pipeline:
  slack:
    image: plugins/slack
    channel: dev
    secrets: [ slack_webhook ]
    when:
      status: [ success, failure ]
