kind: pipeline
name: default

steps:
- name: build api
  image: plugins/docker
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: docker.coroutine.dev/todogo_api
    context: .
    dockerfile: ./Dockerfile
    registry: docker.coroutine.dev
    auto_tag: true
