version: '2'

services:

  api:
    container_name: api
    restart: always
    build: .
    env_file: .environment
    volumes:
      - .:/go/src/github.com/kgantsov/todogo/
    expose:
      - "8080/tcp"
    ports:
      - "8080:8080"
    links:
      # - postgres:postgres
      - cockroach:cockroach
    depends_on:
      # - postgres
      - cockroach
    command: /go/src/github.com/kgantsov/todogo/todogo

#  postgres:
#    container_name: postgres
#    restart: always
#    build: ./docker/postgres
#    volumes:
#      - postgresdatavolume:/var/lib/postgresql
#    ports:
#      - "5432:5432"
#    expose:
#      - "5432/tcp"

  cockroach:
    container_name: cockroach
    restart: always
    image: cockroachdb/cockroach:latest
    volumes:
      - cockroachdatavolume:/cockroach/cockroach-data
    ports:
      - "26257:26257"
    expose:
      - "26257/tcp"
    command: start --insecure
  
  # psql:
  #   container_name: psql
    
  #   image: jbergknoff/postgresql-client

volumes:
  postgresdatavolume:
    driver: local
  cockroachdatavolume:
    driver: local
