version: '2'

services:

  api:
    container_name: api
    restart: always
    build: .
    env_file: .environment
    volumes:
      - .:/go/src/github.com/kgantsov/todogo/
    expose:
      - "8080/tcp"
    ports:
      - "8080:8080"
    links:
      - postgres:postgres
    depends_on:
      - postgres
    command: /go/src/github.com/kgantsov/todogo/todogo

  postgres:
    container_name: postgres
    restart: always
    build: ./docker/postgres
    volumes:
      - postgresdatavolume:/var/lib/postgresql
    ports:
      - "5432:5432"
    expose:
      - "5432/tcp"

volumes:
  postgresdatavolume:
    driver: local
